<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?=isset($title) ? $title : 'Error !'?></title>
        <link rel="stylesheet" href="<?=url_static('css/error.css')?>" type="text/css" />
    </head>
    <body>
        <? partial('error/_' . (isset($code) ? $code : 404)) ?>
        <? if (! PRODUCTION || _g('debug') === 'yes'): ?>
        <div id="runtime-info">
            <? partial('runtime/trace') ?>
            <? partial('runtime/profiler') ?>
        </div>
        <? endif; ?>
    </body>
</html>
