<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}<title>{{ title }}</title>{% endif %}
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <meta name="screen-orientation" content="portrait">
        <meta name="x5-orientation" content="portrait">
        <meta name="format-detection" content="telephone=no" />
        <link rel="Shortcut Icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" type="text/css" href="<?=url_static('lib/layui/css/layui.css')?>" />
        <link rel="stylesheet" href="<?=url_css('error.css')?>" type="text/css" />
    </head>
    <body>
