<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <meta name="screen-orientation" content="portrait">
        <meta name="x5-orientation" content="portrait">
        <meta name="format-detection" content="telephone=no" />
       {% block title %}{{ title }}{% endblock %}
        <link rel="stylesheet" type="text/css" href="/watermark/css/style.css?{{ update_time }}" />
        <script type="text/javascript" src="/watermark/js/scale.js?{{ update_time }}"></script>
        <link rel="stylesheet" type="text/css" href="/watermark/css/m-plus.css?{{ update_time }}" />
    </head>
    <body>
